import Vue from 'vue'   //引入Vue
import VueRouter from 'vue-router'  //引入vue-router

Vue.use(VueRouter); //Vue全局使用Router

export default new VueRouter({
    routes:[
        {
            //主页
            path:'/',
            name:'mainView',
            component:()=>import('../components/mainView.vue')
        },
        {
            //登录
            path:'/login',
            name:'login',
            component:()=>import('../components/login.vue')
        },
        {
            //修改密码
            path:'/passwordModify',
            name:'passwordModify',
            component:()=>import('../components/passwordModify.vue')
        },
        {
            //充值模块
            path:'/pay',
            name:'pay',
            component:()=>import('../components/pay.vue')
        },
        /*****************药品模块*******************/
        {
            //药品查询
            path:'/drug/queryDrug',
            name:'queryDrug',
            component:()=>import('../components/drug/drugSearch.vue')
        },
        {
            //药品详情
            path:'/drug/drugDetail',
            name:'drugDetail',
            component:()=>import('../components/drug/drugDetail.vue')
        },
        {
            //药品修改
            path:'/drug/drugModify',
            name:'drugModify',
            component:()=>import('../components/drug/drugModify.vue')
        },
        {
            //添加药品
            path:'/drug/addNewDrug',
            name:'addNewDrug',
            component:()=>import('../components/drug/addNewDrug.vue')
        },
        {
            //药品领用单查询
            path:'/drugRequest/drugRequestSearch',
            name:'drugRequestSearch',
            component:()=>import('../components/drugRequest/drugRequestSearch.vue')
        },
        {
            //添加药品领用单
            path:'/drugRequest/addNewDrugRequest',
            name:'addNewDrugRequest',
            component:()=>import('../components/drugRequest/addNewDrugRequest.vue')
        },
        {
            //药品领用单详情
            path:'/drugRequest/drugRequestDetail',
            name:'drugRequestDetail',
            component:()=>import('../components/drugRequest/drugRequestDetail.vue')
        },
        {
            //药品采购单查询
            path:'/drugProcurement/drugProcurementSearch',
            name:'drugProcurementSearch',
            component:()=>import('../components/drugProcurement/drugProcurementSearch.vue')
        },
        {
            //添加药品采购单
            path:'/drugProcurement/addNewDrugProcurement',
            name:'addNewDrugProcurement',
            component:()=>import('../components/drugProcurement/addNewDrugProcurement.vue')
        },
        {
            //药品采购单详情
            path:'/drugProcurement/drugProcurementDetail',
            name:'drugProcurementDetail',
            component:()=>import('../components/drugProcurement/drugProcurementDetail.vue')
        },
        {
            //添加经销商
            path:'/retailer/addNewRetailer',
            name:'addNewReatailer',
            component:()=>import('../components/retailer/addNewRetailer.vue')
        },
        /*****************引物测序模块*******************/
        {
            //引物查询
            path:'/primer/primerSearch',
            name:'primerSearch',
            component:()=>import('../components/primer/primerSearch.vue')
        },
        {
            //引物详情
            path:'/primer/primerDetail',
            name:'primerDetail',
            component:()=>import('../components/primer/primerDetail.vue')
        },
        //添加新引物
        {
            path:'/primer/addNewPrimer',
            name:'addNewPrimer',
            component:()=>import('../components/primer/addNewPrimer.vue')
        },
        //测序查询
        {
            path:'/sequence/sequenceSearch',
            name:'sequenceSearch',
            component:()=>import('../components/sequence/sequenceSearch.vue')
        },
        //添加新测序申请
        {
            path:'/sequence/addNewSequence',
            name:'addNewSequence',
            component:()=>import('../components/sequence/addNewSequence.vue')
        },
        {
            path:'/sequence/sequenceDetail',
            name:'sequenceDetail',
            component:()=>import('../components/sequence/sequenceDetail.vue')
        },
        /*****************组会模块*******************/
        //组会日程查询
        {
            path:'/conference/conferenceSearch',
            name:'conferenceSearch',
            component:()=>import('../components/conference/conferenceSearch.vue')
        },
        //添加新组会
        {
            path:'/conference/addNewConference',
            name:'addNewConference',
            component:()=>import('../components/conference/addNewConference.vue')
        },
        //组会日程详情
        {
            path:'/conference/conferenceDetail',
            name:'conferenceDetail',
            component:()=>import('../components/conference/conferenceDetail.vue')
        },
        /*****************书籍模块*******************/
        {
            //书籍查询
            path:'/bookManage/bookSearch',
            name:'bookSearch',
            component:()=>import('../components/bookManage/bookSearch.vue')
        },
        {
            //添加书籍
            path:'/bookManage/addNewBook',
            name:'addNewBook',
            component:()=>import('../components/bookManage/addNewBook.vue')
        },
        {
            //书籍详情
            path:'/bookManage/bookDetail',
            name:'bookDetail',
            component:()=>import('../components/bookManage/bookDetail.vue')
        },
        {
            //未还书籍查询
            path:'/bookLend/bookLendSearch',
            name:'bookLendSearch',
            component:()=>import('../components/bookLend/bookLendSearch.vue')
        },
        {
            //未还书籍详情
            path:'/bookLend/bookLendDetail',
            name:'bookLendDetail',
            component:()=>import('../components/bookLend/bookLendDetail.vue')
        },
        /*****************休假模块*******************/
        {
            //休假信息查询
            path:'/vacation/searchVacationInfo',
            name:'searchVacationInfo',
            component:()=>import('../components/vacation/searchVacationInfo.vue')
        },
        {
            //休假信息详情，修改
            path:'/vacation/vacationInfoDetail',
            name:'vacationInfoDetail',
            component:()=>import('../components/vacation/vacationInfoDetail.vue')
        },
        {
            //添加休假信息
            path:'/vacation/addVacationInfo',
            name:'addVacationInfo',
            component:()=>import('../components/vacation/addVacationInfo.vue')
        },
        {
            //休假记录查询
            path:'/vacation/searchVacationRecord',
            name:'searchVacationRecord',
            component:()=>import('../components/vacation/searchVacationRecord.vue')
        },
        {
            //休假记录详情
            path:'/vacation/vacationRecordDetail',
            name:'vacationRecordDetail',
            component:()=>import('../components/vacation/vacationRecordDetail.vue')
        },
        {
            //添加休假记录
            path:'/vacation/addVacationRecord',
            name:'addVacationRecord',
            component:()=>import('../components/vacation/addVacationRecord.vue')
        },
        /*****************设备管理模块*******************/
        {
            //设备查询
            path:'/device/deviceSearch',
            name:'deviceSearch',
            component:()=>import('../components/device/deviceSearch.vue')
        },
        {
            //设备详情
            path:'/device/deviceDetail',
            name:'deviceDetail',
            component:()=>import('../components/device/deviceDetail.vue')
        },
        {
            //设备修改
            path:'/device/deviceModify',
            name:'deviceModify',
            component:()=>import('../components/device/deviceModify.vue')
        },
        {
            //添加设备
            path:'/device/addNewDevice',
            name:'addNewDevice',
            component:()=>import('../components/device/addNewDevice.vue')
        }

    ]
})